/* eslint-disable @typescript-eslint/no-require-imports */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),Module=require('node:module'),path=require('node:path'),React=require('react');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,p)=>m._compile(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,p);
const resolve=Module._resolveFilename;Module._resolveFilename=function(name,parent,...args){return resolve.call(this,name.startsWith('@/')?path.join(__dirname,'..',name.slice(2)):name,parent,...args);};
let host;const hooks={...React,useState(initial){const i=host.cursor++;if(!(i in host.slots))host.slots[i]=typeof initial==='function'?initial():initial;const h=host;return [h.slots[i],v=>h.slots[i]=typeof v==='function'?v(h.slots[i]):v];},useRef(initial){return hooks.useState({current:initial})[0];},useEffect(){host.cursor++;},useMemo(fn){host.cursor++;return fn();}};
const load=Module._load;Module._load=function(name,parent,main){if(['table-chat.tsx','free-dice-tray.tsx'].some(n=>parent?.filename.endsWith(n))){if(name==='react')return hooks;if(name==='sonner')return {toast:{error(){}}};if(name.startsWith('@/components/'))return new Proxy({},{get:(_,key)=>key==='Button'?'button':String(key)});}return load.call(this,name,parent,main);};
const {TableChat}=require('../components/table-chat.tsx'),{FreeDiceTray}=require('../components/free-dice-tray.tsx');Module._load=load;
const {defaultState,initialSurvivor,content}=require('../lib/game.ts');const {readFreeDiceLog}=require('../lib/free-dice.ts');
function elements(n){if(Array.isArray(n))return n.flatMap(elements);if(!n?.props)return [];return [n,...elements(n.props.children)];}const text=n=>n==null||typeof n==='boolean'?'':Array.isArray(n)?n.map(text).join(''):typeof n==='object'?text(n.props?.children):String(n);
function view(fn,props){const h={slots:[],cursor:0};const render=()=>{host=h;h.cursor=0;return fn(props);};return {render,find:p=>elements(render()).find(p)};}
function fixture(){const g=defaultState(),a=content.archetypes[0];g.survivors=[initialSurvivor({name:'Ana',origin:content.origins[1].name,past:'',archetype:a.name,specialty:a.specialties[0].name,freeExperience:'',techniques:[],attributes:{Instinto:1},primary:'',secondary:'',protection:'',personal:''})];return g;}
test('bandeja compõe quantidade por cliques e permite rolar e limpar',()=>{let rolled;const v=view(FreeDiceTray,{disabled:false,onRoll:f=>{rolled=f;return true;}});v.find(n=>n.props['aria-label']==='Adicionar d6').props.onClick();v.find(n=>n.props['aria-label']==='Adicionar d6').props.onClick();v.find(n=>n.props['aria-label']==='Adicionar d8').props.onClick();assert.equal(v.find(n=>n.type==='input').props.value,'2d6 + 1d8');v.find(n=>n.type==='form').props.onSubmit({preventDefault(){}});assert.equal(rolled,'2d6 + 1d8');v.find(n=>n.type==='button'&&text(n)==='Limpar').props.onClick();assert.equal(v.find(n=>n.type==='input').props.value,'');});
test('jogador rola no chat e por comando com autor correto; prévia não pode rolar',()=>{const g=fixture(),id=g.survivors[0].id;const before=structuredClone(g.survivors);const props={game:g,edit:fn=>fn(g),role:'jogador',survivorId:id,onClose(){}};const v=view(TableChat,props);assert.equal(v.find(n=>n.type==='FreeDiceTray').props.onRoll('2d6+3'),true);assert.equal(g.log[0].kind,'rolagem');assert.equal(g.log[0].actorId,id);assert.ok(readFreeDiceLog(g.log[0].text));assert.deepEqual(g.survivors,before);assert.match(text(v.render()),/Rolagem livre/);assert.doesNotMatch(text(v.render()),/Rolagem de Dualidade/);
 v.find(n=>n.type==='textarea').props.onChange({target:{value:'/r d20'}});v.find(n=>n.props['aria-label']==='Enviar mensagem').props.onClick();assert.equal(readFreeDiceLog(g.log[0].text).formula,'1d20');assert.equal(v.find(n=>n.type==='textarea').props.value,'');const preview=view(TableChat,{...props,readOnly:true});assert.equal(preview.find(n=>n.type==='FreeDiceTray'),undefined);
});
