"use client";
import { BookOpen } from "lucide-react";
const rules={
  roll:{title:"Dados de dualidade",points:["Declare a ação, a Dificuldade e o risco antes de rolar. Esperança d12 + Medo d12 + atributo e modificadores; igualar a Dificuldade é sucesso.","Dados iguais são um crítico: sucesso automático, +1 Esperança e −1 Estresse. Esperança dominante concede 1 Esperança; Medo dominante concede 1 Medo ao mestre.","Sucesso com Medo preserva o objetivo e acrescenta uma complicação. Reações não geram Esperança ou Medo. Confira condições e Experiências antes da rolagem."]},
  search:{title:"Buscas e coleta",points:["Itens à vista não exigem busca. A busca específica combina objetivo, item e quantidade antes da resolução; a busca aberta usa a tabela do local.","Só teste o acesso quando houver risco relevante. Sucesso com Medo mantém a quantidade combinada; a complicação é conduzida pelo mestre.","O achado permanece no local até a coleta. Confira destinatários, carga e recipientes; registrar ou coletar novamente não renova o estoque."]},
  travel:{title:"Travessia e grupos",points:["Escolha quem viaja a partir do mesmo hex. O destino precisa ser adjacente e conhecido; a prévia mostra a duração e os compromissos dos participantes.","Com equipes separadas, a viagem pode aguardar conclusão no relógio. O deslocamento só acontece ao concluir; tempo já transcorrido permanece ao interromper.","Restrito impede viajar enquanto a causa persistir. Confira também as condições dos NPCs acompanhantes e a capacidade de transportar a carga."]},
  event:{title:"Etapas e consequências",points:["Apresente sinais, riscos e prazos antes da decisão. Observar algo evidente ou realizar uma ação sem risco não exige teste.","Registre a etapa realmente executada. Manter o evento ativo permite continuar; encerrar conclui a situação. Se o tempo já foi contado, marque essa opção.","Revise os alvos antes de aplicar efeitos: PV, Estresse e Esperança são por alvo; Comida e Água são um total dividido. Prorrogar um prazo não aumenta o tempo gasto na ação."]},
  day:{title:"Encerramento do dia",points:["Confira as necessidades de cada pessoa e a fonte das provisões. Consumo já registrado não deve ser cobrado novamente.","A prévia mostra faltas e pendências antes de confirmar. Provisões prontas e porções com maior risco de perda são usadas primeiro.","O amanhecer avança os estados previstos, incluindo conservação e infecção. Sobreviventes marcam +1 Estresse por não comer e +1 por não beber, somando +2 se faltarem ambos, até 6. Comer ou beber depois não remove Estresse."]},
  conditions:{title:"Condições",points:["Cada condição descreve efeito e forma de remoção. Restrito bloqueia deslocamento; Vulnerável favorece rolagens contra o alvo quando a exposição se aplica.","Confira a causa na rolagem e escolha vantagem ou desvantagem somente quando pertinente. Não aplique o mesmo efeito duas vezes.","Encerre a condição quando sua causa cessar. Condições de cenário não presumem infecção; Exposição tem seu próprio fluxo de tratamento."]},
  shelter:{title:"Obras e trabalho",points:["Confira espaço, materiais e capacidades antes de iniciar a construção ou o reparo. Pessoas comprometidas não podem dedicar o mesmo intervalo a outra tarefa.","Benefícios dependem do estado e da operação da estrutura; instalações que exigem energia ou responsável precisam desses requisitos.","Confira a prévia do turno. Cancelar trabalho conserva o tempo já transcorrido; remover uma estrutura é uma ação diferente."]},
} as const;
export type RuleTopic=keyof typeof rules;
export function RuleHelp({topic}:{topic:RuleTopic}){
 const rule=rules[topic];
 return <details className="rule-help"><summary><BookOpen size={14} aria-hidden="true"/>Consultar regra · {rule.title}</summary><ul>{rule.points.map(p=><li key={p}>{p}</li>)}</ul></details>;
}
